# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\devGuiTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_encoderDevGui(object):
    def setupUi(self, encoderDevGui):
        encoderDevGui.setObjectName(_fromUtf8("encoderDevGui"))
        encoderDevGui.resize(310, 457)
        self.gridLayout = QtGui.QGridLayout(encoderDevGui)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(encoderDevGui)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(encoderDevGui)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(encoderDevGui)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.UnitLabel = QtGui.QLabel(encoderDevGui)
        self.UnitLabel.setText(_fromUtf8(""))
        self.UnitLabel.setObjectName(_fromUtf8("UnitLabel"))
        self.gridLayout.addWidget(self.UnitLabel, 1, 3, 1, 1)
        self.ResolutionLabel = QtGui.QLabel(encoderDevGui)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ResolutionLabel.setFont(font)
        self.ResolutionLabel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ResolutionLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ResolutionLabel.setText(_fromUtf8(""))
        self.ResolutionLabel.setObjectName(_fromUtf8("ResolutionLabel"))
        self.gridLayout.addWidget(self.ResolutionLabel, 1, 1, 1, 1)
        self.TypeLabel = QtGui.QLabel(encoderDevGui)
        self.TypeLabel.setText(_fromUtf8(""))
        self.TypeLabel.setObjectName(_fromUtf8("TypeLabel"))
        self.gridLayout.addWidget(self.TypeLabel, 0, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.gridGroupBox = QtGui.QGroupBox(encoderDevGui)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ActivityLabel = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ActivityLabel.setFont(font)
        self.ActivityLabel.setText(_fromUtf8(""))
        self.ActivityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ActivityLabel.setObjectName(_fromUtf8("ActivityLabel"))
        self.gridLayout_2.addWidget(self.ActivityLabel, 1, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.counterLabel = QtGui.QLabel(self.gridGroupBox)
        self.counterLabel.setText(_fromUtf8(""))
        self.counterLabel.setObjectName(_fromUtf8("counterLabel"))
        self.gridLayout_2.addWidget(self.counterLabel, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.distanceTravelledUnit = QtGui.QLabel(self.gridGroupBox)
        self.distanceTravelledUnit.setText(_fromUtf8(""))
        self.distanceTravelledUnit.setObjectName(_fromUtf8("distanceTravelledUnit"))
        self.gridLayout_2.addWidget(self.distanceTravelledUnit, 6, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridGroupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 2, 1, 1)
        self.SpeedLabel = QtGui.QLabel(self.gridGroupBox)
        self.SpeedLabel.setText(_fromUtf8(""))
        self.SpeedLabel.setObjectName(_fromUtf8("SpeedLabel"))
        self.gridLayout_2.addWidget(self.SpeedLabel, 2, 1, 1, 1)
        self.timeSpentLabel = QtGui.QLabel(self.gridGroupBox)
        self.timeSpentLabel.setText(_fromUtf8(""))
        self.timeSpentLabel.setObjectName(_fromUtf8("timeSpentLabel"))
        self.gridLayout_2.addWidget(self.timeSpentLabel, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.saveDataCheckBox = QtGui.QCheckBox(self.gridGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.saveDataCheckBox.setFont(font)
        self.saveDataCheckBox.setChecked(True)
        self.saveDataCheckBox.setObjectName(_fromUtf8("saveDataCheckBox"))
        self.gridLayout_2.addWidget(self.saveDataCheckBox, 9, 0, 1, 3)
        self.label_8 = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.SpeedUnit = QtGui.QLabel(self.gridGroupBox)
        self.SpeedUnit.setText(_fromUtf8(""))
        self.SpeedUnit.setObjectName(_fromUtf8("SpeedUnit"))
        self.gridLayout_2.addWidget(self.SpeedUnit, 2, 2, 1, 1)
        self.toggleCounterBtn = QtGui.QPushButton(self.gridGroupBox)
        self.toggleCounterBtn.setCheckable(True)
        self.toggleCounterBtn.setObjectName(_fromUtf8("toggleCounterBtn"))
        self.gridLayout_2.addWidget(self.toggleCounterBtn, 0, 0, 1, 3)
        self.MonitorTimeSpinBox = SpinBox(self.gridGroupBox)
        self.MonitorTimeSpinBox.setSuffix(_fromUtf8(""))
        self.MonitorTimeSpinBox.setDecimals(1)
        self.MonitorTimeSpinBox.setMaximum(180.0)
        self.MonitorTimeSpinBox.setProperty("value", 20.0)
        self.MonitorTimeSpinBox.setObjectName(_fromUtf8("MonitorTimeSpinBox"))
        self.gridLayout_2.addWidget(self.MonitorTimeSpinBox, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox, 2, 0, 1, 4)

        self.retranslateUi(encoderDevGui)
        QtCore.QMetaObject.connectSlotsByName(encoderDevGui)

    def retranslateUi(self, encoderDevGui):
        encoderDevGui.setWindowTitle(_translate("encoderDevGui", "Form", None))
        self.label.setText(_translate("encoderDevGui", "Encoder Type ", None))
        self.label_2.setText(_translate("encoderDevGui", "Encoder Resolution", None))
        self.label_4.setText(_translate("encoderDevGui", "pulses per", None))
        self.gridGroupBox.setTitle(_translate("encoderDevGui", "Activity", None))
        self.label_3.setText(_translate("encoderDevGui", "DistanceTravelled", None))
        self.label_6.setText(_translate("encoderDevGui", "Currently", None))
        self.label_7.setText(_translate("encoderDevGui", "min", None))
        self.label_5.setText(_translate("encoderDevGui", "Time Spent", None))
        self.label_10.setText(_translate("encoderDevGui", "min", None))
        self.label_9.setText(_translate("encoderDevGui", "Duration to Monitor", None))
        self.saveDataCheckBox.setText(_translate("encoderDevGui", "Save Data", None))
        self.label_8.setText(_translate("encoderDevGui", "Speed", None))
        self.toggleCounterBtn.setText(_translate("encoderDevGui", "Start Activity Monitor", None))

from acq4.pyqtgraph import SpinBox
